version: '3.9'

services:
  novozh_flask:
    container_name: rore_chat_container
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5005
      - FLASK_ENV=development
    restart: unless-stopped
volumes:
  flaskdb:
    driver: local